# Generated by Django 4.1.5 on 2023-01-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_customuser_managers_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='UserName',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
