# Generated by Django 4.1.5 on 2023-01-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='userID',
        ),
    ]
