# Generated by Django 4.1.5 on 2023-02-28 10:52

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_rename_user_todolist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=todo_app.models.one_week_hence),
        ),
    ]
